"""agrega columna estado a partidos

Revision ID: 54ba0ea2dd71
Revises: 0e0efd554795
Create Date: 2026-10-06 01:14:29.384443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ba0ea2dd71'
down_revision: Union[str, Sequence[str], None] = '0e0efd554795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidos', sa.Column('estado', sa.String(length=20), server_default='Cupos abiertos', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partidos', 'estado')
    # ### end Alembic commands ###
